# Generated by Django 5.2.17 on 2026-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('revenue_paid', models.DecimalField(decimal_places=2, default=0, help_text='Payments received.', max_digits=14)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, help_text='Total of orders created.', max_digits=14)),
                ('quotations', models.PositiveIntegerField(default=0)),
                ('quotations_converted', models.PositiveIntegerField(default=0)),
                ('by_channel', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
