# Generated by Django 5.2.17 on 2026-09-26 09:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Used when no location is specified.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_location')],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Counting'), ('COMPLETED', 'Completed (corrections applied)'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('started_by', models.CharField(blank=True, max_length=255)),
                ('completed_by', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='inventory.stocklocation')),
            ],
            options={
                'permissions': [('complete_stockcount', 'Can complete a stock count (applies corrections)')],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Leave empty if not counted.', max_digits=12, null=True)),
                ('system_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='On hand when the count completed.', max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('count', 'product'), name='count_line_unique_product'), models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', 0), _connector='OR'), name='count_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Physically present and sellable.', max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Promised to orders, not yet dispatched.', max_digits=12)),
                ('damaged', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Physically present, not sellable.', max_digits=12)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, help_text='Alert when available stock falls to this level.', max_digits=12, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Suggested quantity to reorder.', max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.stocklocation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='stock_balance_unique'), models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_on_hand_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_reserved_not_negative'), models.CheckConstraint(condition=models.Q(('damaged__gte', 0)), name='stock_damaged_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_reserved_within_on_hand')],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('OPENING_BALANCE', 'Opening balance (add)'), ('FOUND', 'Found / add stock'), ('LOST', 'Lost / remove stock'), ('DAMAGE', 'Mark as damaged'), ('DAMAGE_WRITE_OFF', 'Write off damaged stock'), ('DAMAGE_RECOVERED', 'Damaged stock is sellable again'), ('RETURN', 'Customer return (sellable)'), ('RETURN_DAMAGED', 'Customer return (damaged)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Always positive; the kind decides the direction.', max_digits=12)),
                ('note', models.CharField(help_text='Why? Required for accountability.', max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocklocation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='adjustment_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CONSUMED', 'Consumed (dispatched)')], default='ACTIVE', max_length=10)),
                ('source_type', models.CharField(max_length=60)),
                ('source_id', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Released automatically after this time.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stocklocation')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='inventory_r_status_8d1db9_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_r_source__5ab223_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bucket', models.CharField(choices=[('ON_HAND', 'On hand'), ('DAMAGED', 'Damaged')], default='ON_HAND', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Signed: positive adds stock, negative removes it.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, help_text="The bucket's total after this movement.", max_digits=12)),
                ('reason', models.CharField(choices=[('PURCHASE_RECEIVED', 'Purchase received'), ('SALE', 'Sale / dispatch'), ('RETURN', 'Customer return'), ('DAMAGE', 'Marked damaged'), ('DAMAGE_WRITE_OFF', 'Damaged stock written off'), ('DAMAGE_RECOVERED', 'Damaged stock recovered'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('MANUAL_ADJUSTMENT', 'Manual adjustment'), ('STOCKTAKE_CORRECTION', 'Stock count correction'), ('OPENING_BALANCE', 'Opening balance')], max_length=24)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_type', models.CharField(blank=True, max_length=60)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin / staff'), ('SYSTEM', 'System'), ('AGENT', 'AI agent'), ('INTEGRATION', 'Integration')], max_length=16)),
                ('actor_label', models.CharField(max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['product', 'location', 'id'], name='inventory_s_product_fcf1af_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_s_source__18ec1c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_not_zero')],
            },
        ),
    ]
