# Generated by Django 5.2.17 on 2026-09-26 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=10)),
                ('provider_message_id', models.CharField(max_length=150, unique=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False, help_text='Answered by staff or the sales agent.')),
                ('handled_by', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('to', models.CharField(help_text='Phone (E.164 digits) or email address.', max_length=254)),
                ('template', models.CharField(help_text='What kind of message, e.g. order_confirmed.', max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=10)),
                ('backend', models.CharField(blank=True, help_text='Adapter that sent it.', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=60)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_8d5bf0_idx'), models.Index(fields=['related_type', 'related_id'], name='notificatio_related_280496_idx')],
            },
        ),
    ]
