# Generated by Django 5.2.17 on 2026-09-26 09:23

import apps.pricing.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        # Needed for the no-overlapping-price-periods exclusion constraint (= on uuid/bigint + && on ranges).
        BtreeGistExtension(),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='e.g. retail, contractor', max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('prices_include_vat', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_price_list')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, help_text='Empty = current price.', null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. admin, import:12', max_length=60)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'price_list', '-valid_from'],
                'indexes': [models.Index(fields=['product', 'price_list', 'valid_to'], name='pricing_pro_product_888026_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='price_amount_positive'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='price_valid_to_after_valid_from'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('product', '='), ('price_list', '='), (apps.pricing.models.TsTzRange('valid_from', 'valid_to', models.Value('[)')), '&&')], name='price_periods_do_not_overlap')],
            },
        ),
    ]
