# Generated by Django 5.2.17 on 2026-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(default='Dewmix Hardware', max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('whatsapp_sales_number', models.CharField(help_text='International format without +, e.g. 254787151516. Used for quote links.', max_length=20)),
                ('other_phone_numbers', models.JSONField(blank=True, default=list, help_text='JSON list, e.g. ["254743448862"].')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('opening_hours', models.JSONField(blank=True, default=list, help_text='schema.org style, e.g. ["Mo-Fr 07:00-18:00", "Sa 07:00-17:00"].')),
                ('show_prices_online', models.BooleanField(default=False, help_text='Show list prices on the public website/API. Off: every price is on request.')),
                ('quote_validity_days', models.PositiveSmallIntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business profile',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='business_profile_singleton')],
            },
        ),
    ]
