# Generated by Django 5.2.17 on 2026-09-26 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('PICKUP', 'Customer collects'), ('DELIVERY', 'We deliver')], max_length=10)),
                ('status', models.CharField(choices=[('PICKING', 'Picking'), ('PACKED', 'Packed, ready'), ('DISPATCHED', 'Out for delivery / collected'), ('DELIVERED', 'Delivered')], default='PICKING', max_length=10)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(blank=True, help_text='Who received the goods.', max_length=100)),
                ('delivery_notes', models.TextField(blank=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('released_unpaid_by', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment', to='sales.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('dispatch_unpaid', 'Can release goods before full payment (account customers)')],
            },
        ),
    ]
