# Generated by Django 5.2.17 on 2026-09-26 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('name', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Agents ship disabled; switch on one at a time.')),
                ('provider', models.CharField(default='anthropic', max_length=20)),
                ('model', models.CharField(default='claude-opus-5', max_length=60)),
                ('effort', models.CharField(default='medium', help_text='low | medium | high | xhigh | max', max_length=10)),
                ('max_steps', models.PositiveSmallIntegerField(default=8, help_text='Model calls per run.')),
                ('max_output_tokens', models.PositiveIntegerField(default=4000, help_text='Per model call.')),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('daily_budget_usd', models.DecimalField(decimal_places=2, default=5, help_text='Auto-disables above.', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('ESCALATED', 'Handed to a person'), ('FAILED', 'Failed'), ('BLOCKED', 'Not started (disabled / over budget)')], default='RUNNING', max_length=10)),
                ('trigger', models.CharField(help_text='e.g. whatsapp:inbound:123, beat:daily, admin', max_length=60)),
                ('task', models.TextField(help_text='What the agent was asked to do.')),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('steps', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('stop_reason', models.CharField(blank=True, max_length=30)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_calls', to='ai.agentrun')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(max_length=60)),
                ('tier', models.CharField(max_length=10)),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error (reported to the model)'), ('DENIED', 'Denied (not allowed)'), ('PENDING_APPROVAL', 'Sent for approval')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai.agentrun')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
    ]
