# Generated by Django 5.2.17 on 2026-09-26 09:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin / staff'), ('SYSTEM', 'System'), ('AGENT', 'AI agent'), ('INTEGRATION', 'Integration')], max_length=16)),
                ('actor_label', models.CharField(max_length=255)),
                ('actor_user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('agent_run_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('after', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx')],
            },
        ),
    ]
