# Generated by Django 5.2.17 on 2026-09-26 09:39

import apps.catalog.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated: review the report, then approve'), ('COMMITTING', 'Importing'), ('COMMITTED', 'Imported'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled back')], default='UPLOADED', max_length=12)),
                ('update_existing', models.BooleanField(default=False, help_text='Apply changes to existing products. Off: differences become proposals for review instead.')),
                ('activate_new', models.BooleanField(default=False, help_text='Publish new products immediately. Off: they are created as drafts.')),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_by', models.CharField(blank=True, max_length=255)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at'],
                'permissions': [('commit_importbatch', 'Can approve and import a validated spreadsheet'), ('rollback_importbatch', 'Can roll back an imported spreadsheet')],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.catalog.models.media_upload_path)),
                ('content_type', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('original_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable machine name, e.g. diameter_mm.', max_length=60, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('CHOICE', 'Choice from a list'), ('BOOLEAN', 'Yes / no')], max_length=10)),
                ('unit', models.CharField(blank=True, help_text='Display unit for NUMBER, e.g. mm, bar, L.', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='For CHOICE: a JSON list, e.g. ["PN16","PN20"].')),
                ('is_filterable', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, help_text='Where this attribute applies. Empty = all categories.', related_name='attribute_definitions', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Internal SKU, e.g. DWX-0001. Upper-case.', max_length=64, unique=True)),
                ('legacy_id', models.PositiveIntegerField(blank=True, help_text='Id in the original static website. Old WhatsApp quote links use it; never reuse one.', null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (not visible to customers)'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived (no longer sold)')], default='DRAFT', max_length=16)),
                ('unit_of_measure', models.CharField(choices=[('PIECE', 'Piece'), ('PAIR', 'Pair'), ('SET', 'Set'), ('METRE', 'Metre'), ('LENGTH', 'Length (e.g. 6 m pipe)'), ('ROLL', 'Roll'), ('SHEET', 'Sheet'), ('KG', 'Kilogram'), ('BAG', 'Bag'), ('LITRE', 'Litre'), ('TIN', 'Tin'), ('BOX', 'Box'), ('PACKET', 'Packet')], default='PIECE', max_length=16)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('colour', models.CharField(blank=True, max_length=60)),
                ('size_label', models.CharField(blank=True, help_text='Free text size, e.g. "1/2 inch", "20mm".', max_length=60)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('barcode', models.CharField(blank=True, help_text='GTIN/EAN if known.', max_length=32, null=True, unique=True)),
                ('price_on_request', models.BooleanField(default=True, help_text='Always quote this item individually, even if a list price exists.')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='Spreadsheet row number (header is row 1).')),
                ('raw', models.JSONField(default=dict)),
                ('normalized', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('CREATE', 'New product'), ('UPDATE', 'Update existing product'), ('PROPOSE', 'Differences proposed for review'), ('UNCHANGED', 'No change'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate SKU in this file')], max_length=10)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('applied', models.BooleanField(default=False)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('created_price_id', models.UUIDField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.importbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='CatalogReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DUPLICATE_IMAGE', 'Same image on several products'), ('DUPLICATE_NAME', 'Several products with the same name'), ('TRUNCATED_NAME', 'Name looks cut off'), ('MISSING_IMAGE', 'No image'), ('GENERIC_CATEGORY', 'Catch-all subcategory'), ('SUSPICIOUS_VALUE', 'Suspicious value'), ('OTHER', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed (not a problem)')], default='OPEN', max_length=12)),
                ('fingerprint', models.CharField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, help_text='What detected it, e.g. legacy_import.', max_length=60)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('products', models.ManyToManyField(blank=True, related_name='review_items', to='catalog.product')),
            ],
            options={
                'ordering': ['status', 'kind', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogChangeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=40)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('proposed_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(help_text='e.g. legacy_import, catalogue_agent', max_length=60)),
                ('proposed_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPLIED', 'Approved and applied'), ('REJECTED', 'Rejected'), ('STALE', 'Stale (value changed since proposed)')], default='PENDING', max_length=10)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_proposals', to='catalog.product')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'permissions': [('decide_catalogchangeproposal', 'Can approve or reject catalogue change proposals')],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product aliases',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.attributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=255, upload_to='product-documents/%Y/%m/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='families', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'product families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productfamily'),
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('LEGACY_SKU', 'Legacy SKU'), ('ALIAS_SKU', 'Alternative SKU'), ('GTIN', 'GTIN / EAN (additional)'), ('MANUFACTURER_PART', 'Manufacturer part number')], max_length=24)),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='catalog.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product media',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='category_unique_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='category_unique_top_level_name'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='import_row_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='catalogchangeproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('product', 'field', 'source'), name='one_pending_proposal_per_field_and_source'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('text'), models.F('product'), name='alias_unique_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='attribute_value_unique_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', True), ('value_number__isnull', True), ('value_text__isnull', False)), models.Q(('value_bool__isnull', True), ('value_number__isnull', False), ('value_text__isnull', True)), models.Q(('value_bool__isnull', False), ('value_number__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='attribute_value_exactly_one'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='catalog_pro_status_9b3667_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sku', django.db.models.functions.text.Upper('sku'))), name='product_sku_upper_case'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='product_sku_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(fields=('kind', 'value'), name='identifier_unique_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('value', django.db.models.functions.text.Upper('value'))), name='identifier_value_upper_case'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(fields=('product', 'asset'), name='media_asset_once_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='media_one_primary_per_product'),
        ),
    ]
