# Generated by Django 5.2.17 on 2026-09-26 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text='Registered action code, e.g. pricing.set_price', max_length=60)),
                ('summary', models.CharField(max_length=300)),
                ('proposed_values', models.JSONField(help_text='What was asked for.')),
                ('final_values', models.JSONField(blank=True, help_text='What was actually executed (may be edited).', null=True)),
                ('reason', models.TextField(blank=True, help_text='Why the requester wants this.')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Waiting for approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXECUTED', 'Approved and done'), ('FAILED', 'Approved, but failed to execute')], default='PENDING_APPROVAL', max_length=20)),
                ('requested_by', models.CharField(max_length=255)),
                ('agent_run_id', models.CharField(blank=True, max_length=64)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'permissions': [('decide_approvalrequest', 'Can approve or reject automation requests')],
            },
        ),
        migrations.CreateModel(
            name='AutomationSwitch',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('all_disabled', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='automation_switch_singleton')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('fingerprint', models.CharField(max_length=200)),
                ('source', models.CharField(help_text='What raised it: a check, an agent, a task.', max_length=60)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', '-last_seen_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RESOLVED'), _negated=True), fields=('fingerprint',), name='one_unresolved_incident_per_fingerprint')],
            },
        ),
        migrations.CreateModel(
            name='InternalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('related_type', models.CharField(blank=True, max_length=60)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('created_by', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
