# Generated by Django 5.2.17 on 2026-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('terms', models.CharField(help_text='Comma-separated, e.g. tap, faucet, mfereji', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['terms'],
            },
        ),
    ]
