# Generated by Django 5.2.17 on 2026-09-26 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CONTRACTOR', 'Contractor / fundi'), ('BUSINESS', 'Business')], default='INDIVIDUAL', max_length=12)),
                ('phone', models.CharField(blank=True, help_text='E.164 without +, e.g. 254712345678.', max_length=16, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kra_pin', models.CharField(blank=True, help_text='For tax invoices.', max_length=20, verbose_name='KRA PIN')),
                ('address', models.TextField(blank=True)),
                ('whatsapp_opt_in', models.BooleanField(default=False, help_text='Agreed to receive WhatsApp messages from us.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('phone', ''), _negated=True), name='customer_phone_null_not_empty')],
            },
        ),
    ]
