# Generated by Django 5.2.17 on 2026-09-26 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('BANK', 'Bank transfer'), ('CARD', 'Card')], max_length=8)),
                ('state', models.CharField(choices=[('PENDING', 'Pending (waiting for customer/provider)'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed / cancelled')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payer_phone', models.CharField(blank=True, max_length=16)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.CharField(max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Reversal / transfer reference.', max_length=100)),
                ('recorded_by', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('record_refund', 'Can record refunds')],
            },
        ),
        migrations.CreateModel(
            name='InboundPaymentEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=150)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored (duplicate / unknown)'), ('FAILED', 'Processing failed')], default='RECEIVED', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='payment_event_unique')],
            },
        ),
    ]
