# Generated by Django 5.2.17 on 2026-09-26 10:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('ALLOCATED', 'Stock allocated'), ('PICKING', 'Picking'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched / collected'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment in progress'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('channel', models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('WALK_IN', 'Walk-in / counter'), ('PHONE', 'Phone'), ('AGENT', 'AI sales agent')], default='WALK_IN', max_length=10)),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Customer collects'), ('DELIVERY', 'We deliver')], default='PICKUP', max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('prices_include_vat', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line totals when confirmed.', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('cancel_order', 'Can cancel orders')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='status', help_text='status | payment_status | note', max_length=20)),
                ('from_value', models.CharField(blank=True, max_length=20)),
                ('to_value', models.CharField(blank=True, max_length=20)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin / staff'), ('SYSTEM', 'System'), ('AGENT', 'AI agent'), ('INTEGRATION', 'Integration')], max_length=16)),
                ('actor_label', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.order')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to order')], default='DRAFT', max_length=10)),
                ('channel', models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('WALK_IN', 'Walk-in / counter'), ('PHONE', 'Phone'), ('AGENT', 'AI sales agent')], default='WALK_IN', max_length=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Shown to the customer.')),
                ('internal_notes', models.TextField(blank=True)),
                ('prices_include_vat', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_by_agent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quotation',
            field=models.OneToOneField(blank=True, help_text='A quotation converts into at most one order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='sales.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount for this line.', max_digits=12)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount for this line.', max_digits=12)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='order_line_unique_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__isnull', False)), name='order_line_priced'), models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='order_discount_not_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='order_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__gte', 0)), name='order_refunded_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__lte', models.F('amount_paid'))), name='order_refund_within_paid'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'product'), name='quote_line_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='quote_price_ok'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='quote_discount_not_negative'),
        ),
    ]
